project_name: ebs-exporter

gitea_urls:
  api: https://git.maych.in/api/v1/
  download: https://api.maych.in
  skip_tls_verify: false

release:
  gitea:
    owner: thunderbottom
    name: ebs-exporter

builds:
  - # Build macOS, Linux and Windows versions
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    targets:
      - linux_amd64
      - darwin_amd64
      - windows_amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X "main.buildVersion={{ .Tag }}({{ .ShortCommit }})" -X main.buildDate={{ .Date }}

archives:
  - # Replacements for GOOS and GOARCH in the archive name.
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      amd64: x86_64

    # Can be used to change the archive formats for specific GOOS.
    format_overrides:
      - goos: windows
        format: zip

    # Additional files/template/globs you want to add to the archive.
    files:
      - config.toml.example
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^*.md:"
